# Mémoire allouée au démon Gradle (augmenter si la compilation manque de mémoire).
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Bibliothèques AndroidX obligatoires.
android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
